name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy==1.26.4
    - pandas==2.2.2
    - matplotlib==3.10.6
    - ipywidgets==8.1.5
    - itables==2.2.4
    - astropy==6.1.7
    - requests==2.32.3
    - ipympl==0.9.7
